Add PDF Generation and update OpenAPI spec
o2r-project/api pull request #98
Opened 2021-04-16 14:34 UTC by Fmazin

This PR will resolve #90, #92, #94 and #97.

A PDF version of the OpenAPI specification will now be created every time the repository is changed. A preview to the pdf can be viewed [here](https://fmazin.github.io/api/docs/pdf/o2r-openapi.pdf).

In addition to this, bindings are now in the spec. Timestamps have also been reworked.

2021-04-16 15:22 UTC, nuest requested changes
- Fix title for publishment, delete shipment... there are a bunch of headlines with `_` underscores - is this correct? `create_job`, `list_job`, `update_metadata`, `shipment_status`, `publish_deposition`, `xyz_binding`, `list_user`, ...
  ![image](https://user-images.githubusercontent.com/1325054/115043233-9382a480-9ed4-11eb-8c8f-c356ecd19aac.png)
  
  ![image](https://user-images.githubusercontent.com/1325054/115043337-b614bd80-9ed4-11eb-9d86-83ed21ee3c7e.png)
  
  ![image](https://user-images.githubusercontent.com/1325054/115043689-11df4680-9ed5-11eb-8040-3fc0a5a55127.png)

- Fix problem with bold (?) font (in a headline?)
  ![image](https://user-images.githubusercontent.com/1325054/115043468-d5abe600-9ed4-11eb-80aa-951423243a8f.png)
  
  ![image](https://user-images.githubusercontent.com/1325054/115043539-e3fa0200-9ed4-11eb-9ba0-4f460ab1ff7c.png)

- Fix typo "list_reciepients"

---------

I have put some things into this issue - we don't need to fix everything now but can iterate later: https://github.com/o2r-project/api/issues/99

2021-04-16 15:22 UTC, nuest commented on docs/o2r-openapi.yml
> +          The Bindning to be uploaded.
Typo, "Binding".

2021-04-16 15:22 UTC, nuest commented on docs/o2r-openapi.yml
> +#
If it's deprecated, can we not remove this function?

2021-04-20 15:39 UTC, Fmazin reviewed
I have removed the extract binding section and fixed the bold sections. I have done the latter with the command line editor from perl which allows for rather simple and elegant regex search and replace. The headings with `_` are still a Problem but i will probably use also some regex.

2021-04-21 10:44 UTC, nuest commented
@Fmazin let me know when I can take another look.

Also, I guess it would be wise to work in branches that are not `master` from now on to avoid PDF generation while developing the PR, see [`9ea1c10` (#98)](https://github.com/o2r-project/api/pull/98/commits/9ea1c101dd6c3e6b36abae2e970604c683331393)

![image](https://user-images.githubusercontent.com/1325054/115541389-5a18b300-a29f-11eb-9f88-468a15f2323f.png)

2021-05-26 09:46 UTC, nuest commented
@Fmazin Ready to be merged?

2021-05-28 11:55 UTC, Fmazin commented
Yes this is ready to be merged.

2021-06-03 14:09 UTC, nuest approved these changes

2021-06-03 14:09 UTC, merged